# This file has been generated by configure.pl
# please to NOT change by hand, or at least check again
# with configure.pl if you do edit by hand, in order to 
# check that all the variables are correct
# 

$database=			"ipmanage";
$flatdb=			"";
$dbuser=			"root";
$dbpasswd=			"Secret!";
$mysql=				1;
$INSTALLDIR=			"/opt/ipmanage";			

$ipmanage_stderr=		"/tmp/ipmanage.stderr";
$debug=				0;

# the new hosts file that's writtin each time by a cronjob.
$hostfile=			"/etc/hosts";

$site=				"mydomain";

$mailprog=			"/usr/lib/sendmail -t";
$public_dns_manager=		"pdenijs";
$local_dns_manager=		"pdenijs";
$admin_email=			"pdenijs";

$logdir=			"../log";

# for the ping programs
$max_db_connections=		512;			# also the max pings in parallel .... set in /var/mysql/my.cnf max_connections = (yeah, and then some more) 
$ping_timeout=			3;			# ping timeout 3 seconds

# for the zone creation: (ipmanage_write_dns_files.pl);
$ttl=10800;
$refresh=10800;
$retry=3600;
$expire=604800;
$minimum=86400;
@nameservers=('mars');
@mailservers=('mars');
@forwarders=('192.168.0.1','205.171.2.65','205.171.3.65');
$named_dir="/var/named";
$named_dir="/etc/bind";
$named_conf="/etc/named.conf";
$named_conf="/etc/bind/named.conf";

# these are the alias names of your systems that are local, but have names on the internet.
# if you have a system aliais on the internet and is accessible via tunnelling or redirection on your local gateway, you should specify them here with ttheir LOCAL ip-addresses 
@rpz_hosts=(
['myhttpserver.duckdns.org','192.168.0.16'],
['foo-foo.dynamic-dns.net','192.168.0.16'],
['challenge.puppetlabs.vm','192.168.0.15'],
);

1;
